version: '2'

services:

  jenkins-agent:
    container_name: jenkins-agent
    image: vfarcic/jenkins-swarm-agent
    privileged: true
    environment:
      - COMMAND_OPTIONS=-master ${JENKINS_ADDRESS} -username ${USER} -passwordEnvVariable PASSWORD_ENVVAR
      - PASSWORD_ENVVAR=${PASSWORD}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /workspace:/workspace
    restart: always
